# Fase 2: listener plano interno + listener TLS publico con auth

# No bajar privilegios: necesario para leer los certs del volumen de Caddy
user root

# Listener interno sin TLS para el backend dentro de docker
listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd

# Listener publico con TLS (certificado emitido por Caddy/Let's Encrypt)
listener 8883
protocol mqtt

certfile /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mqtt.espalert.app/mqtt.espalert.app.crt
keyfile  /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mqtt.espalert.app/mqtt.espalert.app.key

require_certificate false
allow_anonymous false
password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
